### ISSUE TITLE
Build command is incorrect

### ISSUE THREAD

**Issue by evroon** [jadarve/lluvia-docs#5]
In the [build instructions](https://lluvia.io/docs/gettingstarted/install_linux/#build-c-libraries), you specify the build command to be: `CC=clang bazel build //cpp/...`, but in the [workflow file](https://github.com/jadarve/lluvia/blob/master/.github/workflows/build.yml), it says: `CC=clang bazel build //lluvia/...`.

It took me a while to figure out that the second one is correct (at least I think so, because there is no `cpp` directory). (I don't have any experience with bazel)

**Comment by jadarve** [comment]
Hi, thanks for spotting the error, I fixed the page.
